import type { MunicipalityConfig } from "../GenericMunicipalityScraper";

/**
 * Türkiye üniversiteleri (devlet + vakıf) — etkinlik/duyuru listeleme sayfaları.
 * AnadoluScraper/BilkentScraper/ITUScraper/BogaziciScraper ayrı concrete class'larla kayıtlı.
 *
 * Her config ÖZEL RECON ile doğrulandı (SSR + gerçek selector). SPA / AJAX / alt-alan-takvim
 * olan üniversiteler (İnönü, Sakarya, Kocaeli, Ege, Muğla, Mersin, GTU, Işık, Maltepe,
 * İ.Aydın, Çankaya, Altınbaş, Yaşar, Çukurova, Gaziantep, Uludağ...) Cheerio ile
 * scrape edilemediğinden DAHİL EDİLMEDİ. Yeni eklemeden önce SSR doğrula + selector ver.
 */
export const UNIVERSITY_CONFIGS: MunicipalityConfig[] = [
  // ── Ankara ──
  {
    source: "UNI_ANKARA",
    displayName: "Ankara Üniversitesi",
    baseUrl: "https://ardek.ankara.edu.tr",
    eventListPath: "https://ardek.ankara.edu.tr/tr/etkinlik-arsivi/",
    city: "Ankara",
    selectors: { card: "article.fusion-post-grid", title: "h2.entry-title a", date: "span.updated", image: "img", link: "h2.entry-title a" },
  },
  {
    source: "UNI_HACETTEPE",
    displayName: "Hacettepe Üniversitesi",
    baseUrl: "https://etkinlikler.hacettepe.edu.tr",
    eventListPath: "https://etkinlikler.hacettepe.edu.tr/",
    city: "Ankara",
    selectors: { card: ".haber_card", title: ".haber_card_baslik", date: ".haber_alt", image: "img", link: ".haber_ayrinti_but a" },
  },
  {
    source: "UNI_ODTU",
    displayName: "ODTÜ",
    baseUrl: "https://www.metu.edu.tr",
    eventListPath: "/announcements/home",
    city: "Ankara",
    selectors: { card: "tbody tr", title: "td.views-field-title a", date: "td.views-field-created", image: "img", link: "td.views-field-title a" },
  },
  {
    source: "UNI_GAZI",
    displayName: "Gazi Üniversitesi",
    baseUrl: "https://gazi.edu.tr",
    eventListPath: "/view/announcement-list/1?type=1",
    city: "Ankara",
    selectors: { card: ".subpage-ann-single", title: ".subpage-ann-link a", date: ".subpage-ann-date", image: "img", link: ".subpage-ann-link a" },
  },
  {
    source: "UNI_ATILIM",
    displayName: "Atılım Üniversitesi",
    baseUrl: "https://www.atilim.edu.tr",
    eventListPath: "/tr/home/event/list",
    city: "Ankara",
    selectors: { card: ".news-card", title: ".news-card-title a", date: ".event-date", image: ".news-card-img img", link: ".news-card-title a" },
  },
  {
    source: "UNI_TEDU",
    displayName: "TED Üniversitesi",
    baseUrl: "https://www.tedu.edu.tr",
    eventListPath: "/etkinlikler",
    city: "Ankara",
    selectors: { card: ".event-list", title: "h4 a", date: "time", image: ".event-list img", link: "h4 a" },
  },
  {
    source: "UNI_BASKENT",
    displayName: "Başkent Üniversitesi",
    baseUrl: "https://www.baskent.edu.tr",
    eventListPath: "/tr/etkinlikler",
    city: "Ankara",
    selectors: { card: ".cbp-item", title: ".blog-thumb-desc h5", date: ".category-date", image: ".cbp-caption img", link: ".cbp-caption" },
  },
  {
    source: "UNI_ERBAKAN",
    displayName: "Necmettin Erbakan Üniversitesi",
    baseUrl: "https://erbakan.edu.tr",
    eventListPath: "/tr/etkinlikler",
    city: "Konya",
    selectors: { card: "#duyuru_etkinlik_listele .col-md-12.mb-4", title: ".baslik a", date: ".tarih", venue: ".birim", link: ".baslik a" },
  },
  {
    source: "UNI_SELCUK",
    displayName: "Selçuk Üniversitesi",
    baseUrl: "https://selcuk.edu.tr",
    eventListPath: "/icerik/duyurular",
    city: "Konya",
    // selcuk.edu.tr: eksik ara-sertifika zinciri → undici "fetch failed" (UNABLE_TO_VERIFY_LEAF_SIGNATURE).
    // insecureTLS ile geçilir; tarayıcı UA'sı da veriliyor (bot UA'sını da kısıtlayabiliyor).
    insecureTLS: true,
    headers: { "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36" },
    selectors: { card: ".announcement-card", title: ".announcement-card__title", date: ".announcement-card__date", venue: ".announcement-card__category", link: ".announcement-card__link" },
  },

  // ── İstanbul ──
  {
    source: "UNI_ISTANBUL",
    displayName: "İstanbul Üniversitesi",
    baseUrl: "https://sks.istanbul.edu.tr",
    eventListPath: "https://sks.istanbul.edu.tr/haberler",
    city: "İstanbul",
    selectors: { card: ".news-list li", title: ".news-title", date: ".news-date", image: "img", link: "a.news-list-item" },
  },
  {
    source: "UNI_SABANCI",
    displayName: "Sabancı Üniversitesi",
    baseUrl: "https://www.sabanciuniv.edu",
    eventListPath: "/tr",
    city: "İstanbul",
    selectors: { card: ".mysu-bundle.events .item", title: ".item-title", date: ".item-date", venue: ".location", image: "img[src]", link: "a[href*='events/detail']" },
  },
  {
    source: "UNI_KOC",
    displayName: "Koç Üniversitesi",
    baseUrl: "https://www.ku.edu.tr",
    eventListPath: "/etkinlikler/",
    city: "İstanbul",
    selectors: { card: "article.ku-event-item", title: ".event-list-title", date: ".event-date-time span", venue: ".event-location span", image: "img[src]", link: ".event-list-title a" },
  },
  {
    source: "UNI_GALATASARAY",
    displayName: "Galatasaray Üniversitesi",
    baseUrl: "https://gsu.edu.tr",
    eventListPath: "/tr/guncel",
    city: "İstanbul",
    selectors: { card: ".masonary-item.cat--event", title: ".post-title", date: ".post-date", venue: ".post-categories", image: ".post-feature img", link: ".post-title a" },
  },
  {
    source: "UNI_BAHCESEHIR",
    displayName: "Bahçeşehir Üniversitesi",
    baseUrl: "https://bau.edu.tr",
    eventListPath: "/etkinlikler/",
    city: "İstanbul",
    selectors: { card: ".events-page .box", title: ".location h3", date: ".date", venue: ".location", image: "img.lazyload", link: "a[href^='/etkinlikler/']" },
  },
  {
    source: "UNI_BILGI",
    displayName: "İstanbul Bilgi Üniversitesi",
    baseUrl: "https://www.bilgi.edu.tr",
    eventListPath: "/tr/yasam/duyurular-etkinlikler/",
    city: "İstanbul",
    selectors: { card: ".all-events-item", title: ".text-box h3 a", date: ".date-box", image: ".all-events-item img", link: ".text-box h3 a" },
  },
  {
    source: "UNI_KHAS",
    displayName: "Kadir Has Üniversitesi",
    baseUrl: "https://www.khas.edu.tr",
    eventListPath: "/etkinlikler",
    city: "İstanbul",
    selectors: { card: ".etkinlik-item", title: "a.h5.stretched-link", date: ".badge", image: ".wp-post-image", link: "a.h5.stretched-link" },
  },
  {
    source: "UNI_YEDITEPE",
    displayName: "Yeditepe Üniversitesi",
    baseUrl: "https://www.yeditepe.edu.tr",
    eventListPath: "/tr/etkinlikler",
    city: "İstanbul",
    selectors: { card: ".duyuru-item", title: ".etkinlik-title a", date: ".event-date", venue: ".event-where", image: ".image-wrapper img", link: ".etkinlik-title a" },
  },
  {
    source: "UNI_MEF",
    displayName: "MEF Üniversitesi",
    baseUrl: "https://www.mef.edu.tr",
    eventListPath: "/tr/etkinlikler",
    city: "İstanbul",
    selectors: { card: 'a[href^="/tr/etkinlikler/"]', title: ".text-lg.font-semibold", date: ".text-3xl.font-bold.text-primary", link: 'a[href^="/tr/etkinlikler/"]' },
  },
  {
    source: "UNI_USKUDAR_U",
    displayName: "Üsküdar Üniversitesi",
    baseUrl: "https://uskudar.edu.tr",
    eventListPath: "/etkinlikler",
    city: "İstanbul",
    selectors: { card: ".group", title: "h2 .line-clamp-2", date: "p span.rounded", image: "img", link: 'a[href^="/etkinlik/"]' },
  },
  {
    source: "UNI_ISTINYE",
    displayName: "İstinye Üniversitesi",
    baseUrl: "https://www.istinye.edu.tr",
    eventListPath: "/tr/etkinlikler",
    city: "İstanbul",
    selectors: { card: ".event-item", title: ".event-item--title", date: ".event-item--date", image: "img", link: 'a[href^="/tr/etkinlikler/"]' },
  },
  {
    source: "UNI_MEDIPOL",
    displayName: "İstanbul Medipol Üniversitesi",
    baseUrl: "https://www.medipol.edu.tr",
    eventListPath: "/etkinlikler",
    city: "İstanbul",
    selectors: { card: ".col-lg-4.position-relative", title: ".text-title", date: ".event-item[data-value]", image: "img.lazyload", link: "a.stretched-link" },
  },
  {
    source: "UNI_NISANTASI",
    displayName: "Nişantaşı Üniversitesi",
    baseUrl: "https://www.nisantasi.edu.tr",
    eventListPath: "/etkinlikler",
    city: "İstanbul",
    selectors: { card: ".list-type-item", title: ".events-item-content-title", date: ".events-item-date", image: ".list-type-item-link-image img", link: "a.events-item-link" },
  },
  {
    source: "UNI_MARMARA",
    displayName: "Marmara Üniversitesi",
    baseUrl: "https://www.marmara.edu.tr",
    eventListPath: "/allevents",
    city: "İstanbul",
    selectors: { card: ".schedule-box", title: "h5.title", date: "ul.list-inline li", image: ".thumb img", link: "h5.title a" },
  },
  {
    source: "UNI_YILDIZ",
    displayName: "Yıldız Teknik Üniversitesi",
    baseUrl: "https://www.yildiz.edu.tr",
    eventListPath: "/medya/haberler",
    city: "İstanbul",
    selectors: { card: 'a[href^="/universite/haberler/"]', title: "h3", date: ".date", image: "img.lazyload", link: 'a[href^="/universite/haberler/"]' },
  },
  // UNI_OZYEGIN: FOLLOW-UP — Drupal, .eventListe server-render ama cari ay boş; içerik ?yil=YYYY&ay=MM param'ıyla geliyor. Aylık döngü desteği gerek (generic tek-sayfa çekiyor).
  {
    source: "UNI_OZYEGIN",
    displayName: "Özyeğin Üniversitesi",
    baseUrl: "https://www.ozyegin.edu.tr",
    eventListPath: "/tr/etkinlik",
    city: "İstanbul",
    selectors: { card: ".eventListe li", title: ".title", date: ".date", link: ".title a" },
  },
  {
    source: "UNI_IKU",
    displayName: "İstanbul Kültür Üniversitesi",
    baseUrl: "https://www.iku.edu.tr",
    eventListPath: "/duyurular",
    city: "İstanbul",
    selectors: { card: ".views-row", title: ".views-field-title", date: ".views-field-field-mt-event-date time", link: ".views-field-title a" },
  },

  // ── İzmir ──
  {
    source: "UNI_9EYLUL",
    displayName: "Dokuz Eylül Üniversitesi",
    baseUrl: "https://www.deu.edu.tr",
    eventListPath: "/etkinlikler/",
    city: "İzmir",
    selectors: { card: ".tribe_events", title: "h3.deu-etkinlikler-month-event-title a", link: "h3.deu-etkinlikler-month-event-title a" },
  },
  // UNI_IEU: ".shadow.card.mb-5" arama kutusunu yakalıyordu (yanlış). Etkinlik read-link'e demirlendi, haber karuseli dışlandı. Etkinlik yoksa boş döner (normal).
  {
    source: "UNI_IEU",
    displayName: "İzmir Ekonomi Üniversitesi",
    baseUrl: "https://www.ieu.edu.tr",
    eventListPath: "/tr/events/type/all",
    city: "İzmir",
    selectors: { card: '.filtr-containerV .card:has(a[href*="/events/type/read/"])', title: "h3, h5.card-title", date: ".card-text, .card-footer", image: "img", link: 'a[href*="/events/type/read/"]' },
  },

  // ── Eskişehir ──
  {
    source: "UNI_OSMANGAZI",
    displayName: "Eskişehir Osmangazi Üniversitesi",
    baseUrl: "https://www.ogu.edu.tr",
    eventListPath: "/Web/EtkinlikDetay",
    city: "Eskişehir",
    selectors: { card: "li:has(a[href*='/Web/EtkinlikDetay/'])", title: "a", date: "span.etkinlik-detay-tarih", link: "a[href*='/Web/EtkinlikDetay/']" },
  },
  {
    source: "UNI_ESTU",
    displayName: "Eskişehir Teknik Üniversitesi",
    baseUrl: "https://www.eskisehir.edu.tr",
    eventListPath: "/etkinlik",
    city: "Eskişehir",
    selectors: { card: ".gdlr-core-event-item-list", title: ".gdlr-core-event-item-title a", date: ".gdlr-core-event-item-info.gdlr-core-type-start-date-month", venue: ".gdlr-core-type-location .gdlr-core-tail", image: ".gdlr-core-event-item-thumbnail img", link: ".gdlr-core-event-item-title a" },
  },

  // ── Anadolu / diğer şehirler ──
  {
    source: "UNI_ATATURK",
    displayName: "Atatürk Üniversitesi",
    baseUrl: "https://atauni.edu.tr",
    eventListPath: "/",
    city: "Erzurum",
    selectors: { card: ".haber-card", title: "a.haber-title", date: ".haber-date", image: ".haber-thumb img", link: "a.haber-title" },
  },
  {
    source: "UNI_FIRAT",
    displayName: "Fırat Üniversitesi",
    baseUrl: "https://www.firat.edu.tr",
    eventListPath: "/page/event",
    city: "Elazığ",
    selectors: { card: ".post-item.blog-post-item", title: "h3.title a", date: ".date-block", image: ".item-thumbnail img", link: "h3.title a" },
  },
  {
    source: "UNI_DICLE",
    displayName: "Dicle Üniversitesi",
    baseUrl: "https://www.dicle.edu.tr",
    eventListPath: "/haberler/tumu",
    city: "Diyarbakır",
    selectors: { card: ".newscol", title: "figcaption h5", date: "figcaption h5", image: "figure img", link: "figure a" },
  },
  {
    source: "UNI_OMU",
    displayName: "Ondokuz Mayıs Üniversitesi",
    baseUrl: "https://www.omu.edu.tr",
    eventListPath: "/tr/etkinlikler",
    city: "Samsun",
    selectors: { card: ".ht-item", title: ".ht-heading-title-text a", date: ".ht-timestamp .date-display-single", venue: ".ht-etkinlikturu", image: ".ht-responsive-image img", link: ".ht-heading-title-text a" },
  },
  {
    source: "UNI_ERCIYES",
    displayName: "Erciyes Üniversitesi",
    baseUrl: "https://erciyes.edu.tr",
    eventListPath: "/tr/etkinlikler",
    city: "Kayseri",
    selectors: { card: ".col-lg-3.col-sm-6.mb-5", title: ".fw7.fs15", date: ".fw1.fs14", link: "a.BackgroundS" },
  },
  {
    source: "UNI_PAU",
    displayName: "Pamukkale Üniversitesi",
    baseUrl: "https://www.pau.edu.tr",
    eventListPath: "/pau/tr/duyurular",
    city: "Denizli",
    selectors: { card: "a.item", title: "h6", date: ".publishDate", link: "a.item" },
  },
  {
    source: "UNI_ADU",
    displayName: "Aydın Adnan Menderes Üniversitesi",
    baseUrl: "https://www.adu.edu.tr",
    eventListPath: "/etkinlikler",
    city: "Aydın",
  },
  {
    source: "UNI_AKDENIZ",
    displayName: "Akdeniz Üniversitesi",
    baseUrl: "https://www.akdeniz.edu.tr",
    eventListPath: "/tr/etkinlikler",
    city: "Antalya",
    selectors: { card: "a.list-item", title: ".event-name", date: ".item-dateplace", link: "a.list-item" },
  },
  {
    source: "UNI_COMU",
    displayName: "Çanakkale Onsekiz Mart Üniversitesi",
    baseUrl: "https://www.comu.edu.tr",
    eventListPath: "/ogrenci-kulupleri-haberleri.html",
    city: "Çanakkale",
    selectors: { card: ".haber", title: ".baslik", date: ".tarih", image: ".resim img", link: ".haber a" },
  },
  {
    source: "UNI_DPU",
    displayName: "Kütahya Dumlupınar Üniversitesi",
    baseUrl: "https://www.dpu.edu.tr",
    eventListPath: "/index/etkinlikler",
    city: "Kütahya",
    selectors: { card: "a[href*='/index/etkinlik/']", title: ".baslik", date: ".tarih", link: "a[href*='/index/etkinlik/']" },
  },
  {
    source: "UNI_BANDIRMA",
    displayName: "Bandırma Onyedi Eylül Üniversitesi",
    baseUrl: "https://www.bandirma.edu.tr",
    eventListPath: "/tr",
    city: "Balıkesir",
    selectors: { card: ".eventItem .panel.event", title: ".info a", date: ".rsvp", link: ".info a" },
  },
  {
    source: "UNI_YYU",
    displayName: "Van Yüzüncü Yıl Üniversitesi",
    baseUrl: "https://www.yyu.edu.tr",
    eventListPath: "/",
    city: "Van",
    selectors: { card: "a.ann-link", title: ".ann-date + div", date: ".ann-date", link: "a.ann-link" },
  },
  {
    source: "UNI_RTEU",
    displayName: "Recep Tayyip Erdoğan Üniversitesi",
    baseUrl: "https://www.erdogan.edu.tr",
    eventListPath: "/",
    city: "Rize",
    selectors: { card: "a[href*='Contents.aspx']:has(.tarih)", title: "span", date: ".tarih", link: "a[href*='Contents.aspx']" },
  },
  {
    source: "UNI_GOP",
    displayName: "Tokat Gaziosmanpaşa Üniversitesi",
    baseUrl: "https://www.gop.edu.tr",
    eventListPath: "/TumDuyurular.aspx?d=tr-TR&mk=30541&m=duyuru_tum",
    city: "Tokat",
    selectors: { card: "tr:has(a.events-links)", title: "a.events-links", date: "td:nth-of-type(2)", link: "a.events-links" },
  },
  {
    source: "UNI_HARRAN",
    displayName: "Harran Üniversitesi",
    baseUrl: "https://www.harran.edu.tr",
    eventListPath: "/Etkinlikler",
    city: "Şanlıurfa",
    selectors: { card: ".col-md-6.mb-2 a.ann-link", title: ".ann-date + div", image: ".ann-date img", link: "a.ann-link" },
  },
  {
    source: "UNI_KARADENIZ",
    displayName: "Karadeniz Teknik Üniversitesi",
    baseUrl: "https://www.ktu.edu.tr",
    eventListPath: "/tr/haberler",
    city: "Trabzon",
    selectors: { card: ".haberler", title: "h5", date: "p:nth-of-type(2)", image: "img.haber-img", link: "a[href*='/haber/']" },
  },

  // NOT: Bolu(ibu)/Kars(kafkas)/Muş(alparslan)/Iğdır/Kilis üniversiteleri SSR ve recon'da
  // doğrulandı AMA Vercel sunucu IP'sinden ~10s'de timeout (erişilemiyor/çok yavaş). Bu illerin
  // kapsamı belediye kaynaklarıyla (configs/municipalities.ts → PROVINCIAL) sağlanıyor.
];
