import type { EventListItem } from "./types";

function daysFromNow(n: number, hour = 20, minute = 0): Date {
  const d = new Date();
  d.setDate(d.getDate() + n);
  d.setHours(hour, minute, 0, 0);
  return d;
}

export const MOCK_EVENTS: EventListItem[] = [
  {
    id: "e1",
    slug: "manga-konseri-istanbul",
    source: "BILETIX",
    externalId: "bx-1001",
    title: "maNga • İstanbul Konseri",
    description: "maNga, Volkswagen Arena sahnesinde unutulmaz bir gece için sahne alıyor.",
    category: "KONSER",
    venue: "Volkswagen Arena",
    city: "İstanbul",
    startsAt: daysFromNow(7, 21),
    priceMin: 850,
    priceMax: 1850,
    isFree: false,
    ticketUrl: "https://www.biletix.com/etkinlik/manga",
    imageUrl: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=1200&q=80",
    artist: "maNga",
    featured: true,
    attendeeCount: 248,
    commentCount: 31,
  },
  {
    id: "e2",
    slug: "kadikoy-belediyesi-acik-hava-jazz",
    source: "IBB",
    externalId: "ibb-2001",
    title: "Kadıköy Açık Hava Jazz Akşamı",
    description: "Kadıköy Belediyesi'nin düzenlediği ücretsiz jazz konseri serisinin yeni durağı.",
    category: "KONSER",
    venue: "Kadıköy Halk Eğitim Bahçesi",
    city: "İstanbul",
    startsAt: daysFromNow(3, 20, 30),
    isFree: true,
    imageUrl: "https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?w=1200&q=80",
    featured: true,
    attendeeCount: 612,
    commentCount: 89,
  },
  {
    id: "e3",
    slug: "cem-yilmaz-cmyilmaz-2026",
    source: "BUBILET",
    externalId: "bb-3001",
    title: "Cem Yılmaz • CMYLMZ 2026",
    description: "Cem Yılmaz yeni stand-up gösterisiyle Türkiye turnesinde.",
    category: "STANDUP",
    venue: "Zorlu PSM",
    city: "İstanbul",
    startsAt: daysFromNow(14, 20, 30),
    priceMin: 1250,
    priceMax: 3500,
    isFree: false,
    ticketUrl: "https://bubilet.com.tr/cmylmz",
    imageUrl: "https://images.unsplash.com/photo-1527224857830-43a7acc85260?w=1200&q=80",
    artist: "Cem Yılmaz",
    featured: true,
    attendeeCount: 1043,
    commentCount: 156,
  },
  {
    id: "e4",
    slug: "fenerbahce-galatasaray-derby",
    source: "PASSO",
    externalId: "ps-4001",
    title: "Fenerbahçe – Galatasaray Süper Lig Derbisi",
    description: "Sezonun en kritik derbisi Kadıköy'de.",
    category: "SPOR",
    venue: "Ülker Stadyumu",
    city: "İstanbul",
    startsAt: daysFromNow(21, 19),
    priceMin: 750,
    priceMax: 8500,
    isFree: false,
    ticketUrl: "https://www.passo.com.tr/fb-gs",
    imageUrl: "https://images.unsplash.com/photo-1522778119026-d647f0596c20?w=1200&q=80",
    featured: false,
    attendeeCount: 2890,
    commentCount: 412,
  },
  {
    id: "e5",
    slug: "izmir-uluslararasi-tiyatro-festivali",
    source: "IZMIR_BB",
    externalId: "ibb-5001",
    title: "İzmir Uluslararası Tiyatro Festivali Açılış",
    description: "Festivalin açılış gecesi, dünyaca ünlü topluluğun ücretsiz açık hava gösterisi ile başlıyor.",
    category: "TIYATRO",
    venue: "Konak Meydanı",
    city: "İzmir",
    startsAt: daysFromNow(5, 21),
    isFree: true,
    imageUrl: "https://images.unsplash.com/photo-1503095396549-807759245b35?w=1200&q=80",
    featured: false,
    attendeeCount: 187,
    commentCount: 22,
  },
  {
    id: "e6",
    slug: "tarkan-ankara-konseri",
    source: "MOBILET",
    externalId: "mb-6001",
    title: "Tarkan • Ankara Konseri",
    description: "Megastar Tarkan ATO Congresium sahnesinde.",
    category: "KONSER",
    venue: "ATO Congresium",
    city: "Ankara",
    startsAt: daysFromNow(28, 21),
    priceMin: 1500,
    priceMax: 4500,
    isFree: false,
    ticketUrl: "https://mobilet.com/tarkan",
    imageUrl: "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=1200&q=80",
    artist: "Tarkan",
    featured: true,
    attendeeCount: 1834,
    commentCount: 267,
  },
  {
    id: "e7",
    slug: "ankara-cocuk-tiyatrosu-pinokyo",
    source: "ANKARA_BB",
    externalId: "abb-7001",
    title: "Çocuk Tiyatrosu: Pinokyo",
    description: "Ankara Büyükşehir Belediyesi Şehir Tiyatroları ücretsiz çocuk oyunu.",
    category: "COCUK",
    venue: "Çankaya Kültür Merkezi",
    city: "Ankara",
    startsAt: daysFromNow(2, 14),
    isFree: true,
    imageUrl: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=1200&q=80",
    featured: false,
    attendeeCount: 96,
    commentCount: 14,
  },
  {
    id: "e8",
    slug: "rock-n-coke-2026",
    source: "BILETIX",
    externalId: "bx-8001",
    title: "Rock'n Coke 2026 Festivali",
    description: "Türkiye'nin en büyük rock festivali 3 gün, 6 sahne, 40+ sanatçı.",
    category: "FESTIVAL",
    venue: "KüçükÇiftlik Park",
    city: "İstanbul",
    startsAt: daysFromNow(45, 16),
    priceMin: 2500,
    priceMax: 6500,
    isFree: false,
    ticketUrl: "https://www.biletix.com/rocknckoke",
    imageUrl: "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=1200&q=80",
    featured: true,
    attendeeCount: 3201,
    commentCount: 543,
  },
  {
    id: "e9",
    slug: "modern-sanat-sergisi-pera",
    source: "MANUAL",
    externalId: "mn-9001",
    title: "Modern Sanat Sergisi • Pera Müzesi",
    description: "Çağdaş Türk ressamlarından seçkiler.",
    category: "SERGI",
    venue: "Pera Müzesi",
    city: "İstanbul",
    startsAt: daysFromNow(1, 10),
    endsAt: daysFromNow(60, 18),
    priceMin: 150,
    priceMax: 250,
    isFree: false,
    imageUrl: "https://images.unsplash.com/photo-1577720580479-7d839d829c73?w=1200&q=80",
    featured: false,
    attendeeCount: 67,
    commentCount: 9,
  },
  {
    id: "e10",
    slug: "bursa-uludag-kayak-festivali",
    source: "MANUAL",
    externalId: "mn-9002",
    title: "Uludağ Kış Festivali",
    description: "Uludağ'da müzik, snowboard ve kayak yarışmaları.",
    category: "FESTIVAL",
    venue: "Uludağ Kayak Merkezi",
    city: "Bursa",
    startsAt: daysFromNow(35, 12),
    priceMin: 450,
    priceMax: 1200,
    isFree: false,
    imageUrl: "https://images.unsplash.com/photo-1551524559-8af4e6624178?w=1200&q=80",
    featured: false,
    attendeeCount: 421,
    commentCount: 38,
  },
  {
    id: "e11",
    slug: "ibb-bogazici-kosusu",
    source: "IBB",
    externalId: "ibb-10001",
    title: "Boğaziçi Kıtalararası Halk Koşusu",
    description: "İBB tarafından düzenlenen ücretsiz halk koşusu.",
    category: "SPOR",
    venue: "15 Temmuz Şehitler Köprüsü",
    city: "İstanbul",
    startsAt: daysFromNow(12, 9),
    isFree: true,
    imageUrl: "https://images.unsplash.com/photo-1452626038306-9aae5e071dd3?w=1200&q=80",
    featured: false,
    attendeeCount: 8541,
    commentCount: 124,
  },
  {
    id: "e12",
    slug: "kodluyoruz-atolye-istanbul",
    source: "MANUAL",
    externalId: "mn-9003",
    title: "Kodluyoruz Junior • Çocuk Yazılım Atölyesi",
    description: "9-14 yaş arası çocuklar için ücretsiz Python atölyesi.",
    category: "ATOLYE",
    venue: "İBB Maker Lab",
    city: "İstanbul",
    startsAt: daysFromNow(4, 11),
    isFree: true,
    imageUrl: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=1200&q=80",
    featured: false,
    attendeeCount: 32,
    commentCount: 7,
  },
  {
    id: "e13",
    slug: "anadolu-uni-bahar-senligi",
    source: "ANADOLU_UNI",
    externalId: "anu-12001",
    title: "Anadolu Üniversitesi Bahar Şenliği Açılış Konseri",
    description: "Bahar şenliklerinin ilk gününde öğrenci toplulukları sahnede; ücretsiz açık hava konseri.",
    category: "KONSER",
    venue: "Yunus Emre Kampüsü Açık Hava Tiyatrosu",
    city: "Eskişehir",
    startsAt: daysFromNow(9, 19, 30),
    isFree: true,
    imageUrl: "https://images.unsplash.com/photo-1429962714451-bb934ecdc4ec?w=1200&q=80",
    featured: false,
    attendeeCount: 412,
    commentCount: 26,
  },
  {
    id: "e14",
    slug: "bilkent-fmpa-piyano-resitali",
    source: "BILKENT",
    externalId: "blk-13001",
    title: "Bilkent FMPA • Genç Piyanistler Resitali",
    description: "Bilkent Müzik ve Sahne Sanatları Fakültesi öğrencilerinden ücretsiz piyano resitali.",
    category: "KONSER",
    venue: "Bilkent Konser Salonu",
    city: "Ankara",
    startsAt: daysFromNow(6, 20),
    isFree: true,
    imageUrl: "https://images.unsplash.com/photo-1520523839897-bd0b52f945a0?w=1200&q=80",
    featured: false,
    attendeeCount: 87,
    commentCount: 11,
  },
  {
    id: "e15",
    slug: "itu-yapay-zeka-atolyesi",
    source: "ITU",
    externalId: "itu-14001",
    title: "İTÜ Yapay Zeka Topluluğu • LLM Atölyesi",
    description: "İTÜ AI Society düzenliyor; ücretsiz pratik atölye, kayıt sınırlı.",
    category: "ATOLYE",
    venue: "İTÜ Ayazağa Kampüsü • Elektrik-Elektronik Fakültesi",
    city: "İstanbul",
    startsAt: daysFromNow(8, 14),
    isFree: true,
    imageUrl: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=1200&q=80",
    featured: false,
    attendeeCount: 154,
    commentCount: 19,
  },
  {
    id: "e16",
    slug: "bogazici-mithat-alam-film-sergisi",
    source: "BOGAZICI",
    externalId: "bou-15001",
    title: "Boğaziçi Üniversitesi • Mithat Alam Film Merkezi Afiş Sergisi",
    description: "Türk sinemasından seçilmiş afişlerin yer aldığı ücretsiz sergi; Güney Kampüs.",
    category: "SERGI",
    venue: "Mithat Alam Film Merkezi",
    city: "İstanbul",
    startsAt: daysFromNow(2, 10),
    endsAt: daysFromNow(30, 18),
    isFree: true,
    imageUrl: "https://images.unsplash.com/photo-1485846234645-a62644f84728?w=1200&q=80",
    featured: false,
    attendeeCount: 63,
    commentCount: 5,
  },
  // === ESKISEHIR_BB — Visit Eskişehir gerçek listesinden ===
  { id: "es1", slug: "kucuk-yagmur-damlasi-yaratici-okuma", source: "ESKISEHIR_BB", externalId: "es-101", title: "Küçük Yağmur Damlası - Yaratıcı Okuma Atölyesi", description: "Çocuklara yönelik yaratıcı okuma atölyesi; ücretsiz katılım, kayıt gerek.", category: "ATOLYE", venue: "Eskişehir Büyükşehir Belediyesi", city: "Eskişehir", startsAt: daysFromNow(6, 11), isFree: true, ticketUrl: "https://www.visiteskisehir.org/kategori.php?id=73", imageUrl: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=1200&q=80", featured: false, attendeeCount: 42, commentCount: 3 },
  { id: "es2", slug: "almanca-iletisim-becerileri", source: "ESKISEHIR_BB", externalId: "es-102", title: "Almanca İletişim Becerileri Atölyesi", description: "Başlangıç ve orta seviye katılımcılar için ücretsiz Almanca iletişim atölyesi.", category: "ATOLYE", venue: "Eskişehir Büyükşehir Belediyesi", city: "Eskişehir", startsAt: daysFromNow(10, 14), isFree: true, ticketUrl: "https://www.visiteskisehir.org/kategori.php?id=73", imageUrl: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=1200&q=80", featured: false, attendeeCount: 28, commentCount: 2 },
  { id: "es3", slug: "ahsap-baski-atolyesi", source: "ESKISEHIR_BB", externalId: "es-103", title: "Ahşap Baskı Atölyesi", description: "El emeği ahşap baskı tekniklerini öğrenebileceğin ücretsiz workshop.", category: "ATOLYE", venue: "Tepebaşı Sanat Atölyesi", city: "Eskişehir", startsAt: daysFromNow(11, 15), isFree: true, ticketUrl: "https://www.visiteskisehir.org/kategori.php?id=73", imageUrl: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=1200&q=80", featured: false, attendeeCount: 34, commentCount: 4 },
  { id: "es4", slug: "dengin-ceyhan-resital", source: "ESKISEHIR_BB", externalId: "es-104", title: "Dengin Ceyhan - Piyano Resital", description: "Genç piyanist Dengin Ceyhan'ın klasik repertuvardan oluşan ücretsiz resitali.", category: "KONSER", venue: "Eskişehir Büyükşehir Belediyesi Konser Salonu", city: "Eskişehir", startsAt: daysFromNow(16, 20), isFree: true, ticketUrl: "https://www.visiteskisehir.org/kategori.php?id=73", imageUrl: "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=1200&q=80", featured: false, attendeeCount: 187, commentCount: 18 },
  { id: "es5", slug: "19-mayis-genclik-yuruyusu", source: "ESKISEHIR_BB", externalId: "es-105", title: "19 Mayıs Ruhuyla Gençlik Yürüyüşü", description: "Yeşilyurt–Rızapaşa hattında gençlik yürüyüşü; tüm vatandaşlar davetli.", category: "SPOR", venue: "Yeşilyurt – Rızapaşa", city: "Eskişehir", startsAt: daysFromNow(20, 9), isFree: true, ticketUrl: "https://www.visiteskisehir.org/kategori.php?id=73", imageUrl: "https://images.unsplash.com/photo-1452626038306-9aae5e071dd3?w=1200&q=80", featured: false, attendeeCount: 1240, commentCount: 32 },
  { id: "es6", slug: "eskisehir-cocuk-tiyatrosu", source: "ESKISEHIR_BB", externalId: "es-106", title: "Eskişehir Belediyesi Çocuk Tiyatrosu: Üç Küçük Domuz", description: "Ücretsiz çocuk oyunu, hafta sonu matinesi.", category: "COCUK", venue: "Şehir Tiyatrosu Salon B", city: "Eskişehir", startsAt: daysFromNow(13, 14), isFree: true, ticketUrl: "https://www.visiteskisehir.org/kategori.php?id=73", imageUrl: "https://images.unsplash.com/photo-1503095396549-807759245b35?w=1200&q=80", featured: false, attendeeCount: 96, commentCount: 11 },

  // === MUNI_BURSA — bursa.bel.tr gerçek listesinden ===
  { id: "br1", slug: "hunkar-kosku-zamanin-taniklari", source: "MUNI_BURSA", externalId: "br-201", title: "Hünkâr Köşkü'nde Zamanın Tanıkları", description: "Bursa BB Kültür A.Ş.'nin organize ettiği ücretsiz tarihi mekan turu ve sergi.", category: "SERGI", venue: "Hünkâr Köşkü", city: "Bursa", startsAt: daysFromNow(8, 14), isFree: true, ticketUrl: "https://www.bursa.bel.tr/etkinlik", imageUrl: "https://images.unsplash.com/photo-1577720580479-7d839d829c73?w=1200&q=80", featured: false, attendeeCount: 156, commentCount: 12 },
  { id: "br2", slug: "bursa-konser-osmangazi-acik-hava", source: "MUNI_BURSA", externalId: "br-202", title: "Osmangazi Açık Hava Konseri", description: "Bursa BB Şehir Orkestrası açık hava konseri; ücretsiz.", category: "KONSER", venue: "Osmangazi Meydanı", city: "Bursa", startsAt: daysFromNow(15, 21), isFree: true, ticketUrl: "https://www.bursa.bel.tr/etkinlik", imageUrl: "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=1200&q=80", featured: false, attendeeCount: 540, commentCount: 28 },
  { id: "br3", slug: "uludag-yaz-festivali", source: "MUNI_BURSA", externalId: "br-203", title: "Uludağ Yaz Kültür Festivali", description: "10 günlük kültür sanat festivali; yerel ve uluslararası gruplar.", category: "FESTIVAL", venue: "Uludağ", city: "Bursa", startsAt: daysFromNow(28, 18), isFree: false, priceMin: 50, priceMax: 350, ticketUrl: "https://www.bursa.bel.tr/etkinlik", imageUrl: "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=1200&q=80", featured: true, attendeeCount: 2100, commentCount: 87 },

  // === MUNI_USKUDAR — kültür sanat takvimi ===
  { id: "us1", slug: "uskudar-meydan-konseri", source: "MUNI_USKUDAR", externalId: "us-301", title: "Üsküdar Meydan Konseri - Anadolu Müziği", description: "Üsküdar Belediyesi Anadolu müziği konseri.", category: "KONSER", venue: "Üsküdar Meydanı", city: "İstanbul", startsAt: daysFromNow(5, 20), isFree: true, ticketUrl: "https://uskudar.bel.tr", imageUrl: "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=1200&q=80", featured: false, attendeeCount: 380, commentCount: 21 },
  { id: "us2", slug: "uskudar-tiyatro-eski-istanbul", source: "MUNI_USKUDAR", externalId: "us-302", title: "Eski İstanbul Hikâyeleri", description: "Üsküdar Belediyesi Şehir Tiyatrosu ücretsiz oyun.", category: "TIYATRO", venue: "Üsküdar Belediyesi Sahnesi", city: "İstanbul", startsAt: daysFromNow(12, 19), isFree: true, ticketUrl: "https://uskudar.bel.tr", imageUrl: "https://images.unsplash.com/photo-1503095396549-807759245b35?w=1200&q=80", featured: false, attendeeCount: 145, commentCount: 9 },

  // === MUNI_KADIKOY — kültür sanat ===
  { id: "kd1", slug: "kadikoy-jazz-acik-hava", source: "MUNI_KADIKOY", externalId: "kd-401", title: "Kadıköy Açık Hava Jazz Buluşması", description: "Kadıköy Belediyesi ücretsiz jazz serisi.", category: "KONSER", venue: "Yoğurtçu Parkı", city: "İstanbul", startsAt: daysFromNow(7, 20), isFree: true, ticketUrl: "https://kultursanat.kadikoy.bel.tr/tr/kadikoyde-kultur-sanat", imageUrl: "https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?w=1200&q=80", featured: false, attendeeCount: 412, commentCount: 24 },
  { id: "kd2", slug: "kadikoy-cocuk-soytarsi", source: "MUNI_KADIKOY", externalId: "kd-402", title: "Kadıköy Çocuk Şenliği - Sirk Gösterisi", description: "Kadıköy'deki çocuklara ücretsiz sirk + balon + boyama atölyesi.", category: "COCUK", venue: "Caferağa Spor Salonu", city: "İstanbul", startsAt: daysFromNow(4, 13), isFree: true, ticketUrl: "https://kultursanat.kadikoy.bel.tr/tr/kadikoyde-kultur-sanat", imageUrl: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=1200&q=80", featured: false, attendeeCount: 78, commentCount: 6 },

  // === UNI_SABANCI ===
  { id: "su1", slug: "sabanci-yaz-konseri", source: "UNI_SABANCI", externalId: "su-501", title: "Sabancı Üniversitesi Yaz Konseri", description: "SU müzik topluluğu yaz açık hava konseri.", category: "KONSER", venue: "Tuzla Kampüs Forum", city: "İstanbul", startsAt: daysFromNow(22, 20), isFree: true, ticketUrl: "https://www.sabanciuniv.edu/tr", imageUrl: "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=1200&q=80", featured: false, attendeeCount: 220, commentCount: 14 },
  { id: "su2", slug: "sabanci-mezuniyet-toreni", source: "UNI_SABANCI", externalId: "su-502", title: "SU 2026 Mezuniyet Töreni", description: "Sabancı Üniversitesi 2026 mezuniyet töreni; davetli misafirler.", category: "DIGER", venue: "Tuzla Kampüs", city: "İstanbul", startsAt: daysFromNow(30, 14), isFree: true, ticketUrl: "https://www.sabanciuniv.edu/tr", imageUrl: "https://images.unsplash.com/photo-1429962714451-bb934ecdc4ec?w=1200&q=80", featured: false, attendeeCount: 1840, commentCount: 56 },

  // === BILETINIAL — gerçek site sanatçıları ===
  { id: "bn1", slug: "wolf-alice-konseri", source: "BILETINIAL", externalId: "bn-601", title: "Wolf Alice • İstanbul Konseri", description: "İngiliz alt-rock grubu Wolf Alice İstanbul'da; Biletinial üzerinden bilet.", category: "KONSER", venue: "Volkswagen Arena", city: "İstanbul", startsAt: daysFromNow(27, 21), isFree: false, priceMin: 950, priceMax: 2400, ticketUrl: "https://biletinial.com/tr-tr/muzik/wolf-alice", imageUrl: "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=1200&q=80", featured: true, attendeeCount: 1480, commentCount: 92 },
  { id: "bn2", slug: "in-flames-konseri", source: "BILETINIAL", externalId: "bn-602", title: "In Flames • İstanbul Konseri", description: "İsveçli metal grubu In Flames İstanbul'da.", category: "KONSER", venue: "KüçükÇiftlik Park", city: "İstanbul", startsAt: daysFromNow(33, 20), isFree: false, priceMin: 1200, priceMax: 2800, ticketUrl: "https://biletinial.com/tr-tr/muzik/in-flames-konseri", imageUrl: "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=1200&q=80", featured: false, attendeeCount: 720, commentCount: 48 },

  // === FESTTR ===
  { id: "ft1", slug: "ayvacik-bahar-senligi", source: "FESTTR", externalId: "ft-701", title: "Ayvacık Bahar Şenliği", description: "Samsun Ayvacık'ta geleneksel bahar şenliği; yerel sanatçılar, halay, lezzetler.", category: "FESTIVAL", venue: "Ayvacık Meydanı", city: "Samsun", startsAt: daysFromNow(2, 11), isFree: true, ticketUrl: "https://festtr.com/festival/ayvacik-bahar-senligi/", imageUrl: "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=1200&q=80", featured: false, attendeeCount: 540, commentCount: 23 },
  { id: "ft2", slug: "tirilye-zeytin-cicegi", source: "FESTTR", externalId: "ft-702", title: "Tirilye Zeytin Çiçeği Festivali", description: "Bursa Mudanya Tirilye'de zeytin hasadı festivali; iki gün.", category: "FESTIVAL", venue: "Tirilye", city: "Bursa", startsAt: daysFromNow(3, 12), endsAt: daysFromNow(4, 18), isFree: true, ticketUrl: "https://festtr.com/festival/tirilye-zeytin-cicegi/", imageUrl: "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=1200&q=80", featured: true, attendeeCount: 890, commentCount: 41 },
  { id: "ft3", slug: "antalya-yoruk-turkmen", source: "FESTTR", externalId: "ft-703", title: "Uluslararası Antalya Yörük Türkmen Festivali", description: "Antalya'da geleneksel Yörük-Türkmen festivali; 3 gün.", category: "FESTIVAL", venue: "Konyaaltı", city: "Antalya", startsAt: daysFromNow(3, 17), endsAt: daysFromNow(5, 23), isFree: true, ticketUrl: "https://festtr.com/festival/antalya-yoruk-turkmen/", imageUrl: "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=1200&q=80", featured: true, attendeeCount: 1200, commentCount: 67 },
  { id: "ft4", slug: "manisa-kultur-yolu", source: "FESTTR", externalId: "ft-704", title: "Manisa Kültür Yolu Festivali", description: "Manisa'da 9 gün süren kültür sanat festivali; konserler, atölyeler, sergiler.", category: "FESTIVAL", venue: "Manisa Merkez", city: "Manisa", startsAt: daysFromNow(3, 18), endsAt: daysFromNow(11, 23), isFree: true, ticketUrl: "https://festtr.com/festival/manisa-kultur-yolu/", imageUrl: "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=1200&q=80", featured: false, attendeeCount: 670, commentCount: 28 },
  { id: "ft5", slug: "mihaliccik-kiraz-festivali", source: "FESTTR", externalId: "ft-705", title: "Mihalıççık Kiraz Festivali", description: "Eskişehir Mihalıççık'ta kiraz hasadı kutlaması; canlı müzik, yöresel lezzetler, halay.", category: "FESTIVAL", venue: "Kalburcu Mesire Yeri • Mihalıççık", city: "Eskişehir", startsAt: daysFromNow(18, 11), endsAt: daysFromNow(19, 22), isFree: true, ticketUrl: "https://festtr.com/festival/mihaliccik-kiraz-festivali/", imageUrl: "https://images.unsplash.com/photo-1528821128474-27f963b062bf?w=1200&q=80", featured: false, attendeeCount: 420, commentCount: 18 },
  { id: "ft6", slug: "kapadokya-balon-festivali", source: "FESTTR", externalId: "ft-706", title: "Kapadokya Sıcak Hava Balonu Festivali", description: "Nevşehir Göreme'de 4 günlük sıcak hava balonu festivali; gün doğumu uçuşları, peri bacaları, gece müziği.", category: "FESTIVAL", venue: "Göreme Açık Hava Müzesi • Kapadokya", city: "Nevşehir", startsAt: daysFromNow(25, 6), endsAt: daysFromNow(28, 23), isFree: false, priceMin: 350, priceMax: 1800, ticketUrl: "https://festtr.com/festival/kapadokya-balon-festivali/", imageUrl: "https://images.unsplash.com/photo-1641128324972-af3212f0f6bd?w=1200&q=80", featured: true, attendeeCount: 1850, commentCount: 76 },
  { id: "ft7", slug: "nevsehir-bag-bozumu", source: "FESTTR", externalId: "ft-707", title: "Avanos Bağ Bozumu Şenliği", description: "Nevşehir Avanos bağ bozumu hasat festivali; üzüm ezme, halay, yöresel mutfak.", category: "FESTIVAL", venue: "Avanos • Nevşehir", city: "Nevşehir", startsAt: daysFromNow(40, 14), endsAt: daysFromNow(41, 23), isFree: true, ticketUrl: "https://festtr.com/festival/nevsehir-bag-bozumu/", imageUrl: "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=1200&q=80", featured: false, attendeeCount: 580, commentCount: 24 },
  { id: "ft8", slug: "kapadokya-fotograf-yarismasi", source: "FESTTR", externalId: "ft-708", title: "Kapadokya Fotoğraf Yarışması ve Sergisi", description: "Nevşehir'de gün batımı fotoğraf yarışması + sergi açılışı.", category: "SERGI", venue: "Uçhisar Kalesi", city: "Nevşehir", startsAt: daysFromNow(12, 17), isFree: true, ticketUrl: "https://festtr.com/festival/kapadokya-fotograf/", imageUrl: "https://images.unsplash.com/photo-1641128324972-af3212f0f6bd?w=1200&q=80", featured: false, attendeeCount: 240, commentCount: 8 },
];
