/**
 * FestivallTr scraper'ı çalıştırır ve sonucu
 * src/lib/festivall-events.ts dosyasına statik olarak yazar.
 *
 * Bu dosya production'da `events.ts`'in MOCK_EVENTS'ine ek olarak yüklenir
 * — Vercel cron'una bağlı kalmadan 300+ festival her sayfa açılışında görünür.
 *
 * Yeniden çalıştır: USE_MOCK_DATA=false npx tsx scripts/snapshot-festivall.ts
 */
import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { FestivallTrScraper } from "../src/lib/scrapers/providers/FestivallTrScraper";
import { slugify } from "../src/lib/utils";
import type { EventListItem } from "../src/lib/types";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = join(__dirname, "..", "src", "lib", "festivall-events.ts");

async function main() {
  console.log("\n🎪 FestivallTr snapshot oluşturuluyor...\n");

  const scraper = new FestivallTrScraper();
  const result = await scraper.run();

  if (!result.success) {
    console.error("Scraper başarısız:", result.errorMessage);
    process.exit(1);
  }

  console.log(`  ✓ ${result.events.length} etkinlik alındı`);

  // EventListItem formatına çevir
  const items: EventListItem[] = result.events.map((e, idx) => {
    const slug = `${slugify(e.title)}-${e.externalId.slice(-8)}-${idx}`;
    return {
      id: `festivall-${idx}-${e.externalId}`,
      slug,
      source: e.source,
      externalId: e.externalId,
      title: e.title,
      description: e.description,
      category: e.category,
      venue: e.venue,
      city: e.city,
      district: e.district,
      startsAt: e.startsAt,
      endsAt: e.endsAt,
      priceMin: e.priceMin,
      priceMax: e.priceMax,
      isFree: e.isFree,
      ticketUrl: e.ticketUrl,
      imageUrl: e.imageUrl,
      artist: e.artist,
      featured: false,
      attendeeCount: 25 + Math.floor(Math.random() * 200),
      commentCount: Math.floor(Math.random() * 20),
    };
  });

  // Date alanlarını JSON.stringify'dan önce sentinel placeholder'a çevir,
  // sonra sentinel'i `new Date(...)` ifadesiyle değiştir.
  // (JSON.stringify replacer Date'i yakalayamaz çünkü Date.prototype.toJSON
  // önce string'e çevirir.)
  const tsLiteral = items
    .map((it) => {
      const sentinel = {
        ...it,
        startsAt: { __D__: it.startsAt.toISOString() },
        endsAt: it.endsAt ? { __D__: it.endsAt.toISOString() } : undefined,
      };
      const j = JSON.stringify(sentinel);
      return j.replace(/\{"__D__":"([^"]+)"\}/g, 'new Date("$1")');
    })
    .join(",\n  ");

  const fileContent = `/**
 * AUTOGENERATED — festivall.com.tr scraper snapshot'ı.
 * Yenilemek için:
 *   USE_MOCK_DATA=false npx tsx scripts/snapshot-festivall.ts
 *
 * ${items.length} etkinlik · ${new Date().toLocaleDateString("tr-TR")} alındı.
 * Türkiye'nin 81 ilinde duyurulan festivaller.
 */
import type { EventListItem } from "./types";

export const FESTIVALL_EVENTS: EventListItem[] = [
  ${tsLiteral}
];
`;

  await writeFile(OUT, fileContent, "utf8");

  // İstatistik
  const byCity = new Map<string, number>();
  for (const e of items) byCity.set(e.city, (byCity.get(e.city) ?? 0) + 1);
  const top = [...byCity.entries()].sort((a, b) => b[1] - a[1]).slice(0, 10);
  console.log(`\n  Dosya yazıldı: src/lib/festivall-events.ts (${items.length} etkinlik)`);
  console.log(`\n  Top 10 şehir:`);
  for (const [city, n] of top) console.log(`    ${city.padEnd(15)} ${n}`);
  console.log(`\n  Toplam şehir: ${byCity.size}/81`);
}

main().catch((err) => {
  console.error("Hata:", err);
  process.exit(2);
});
